name: CI

env:
  BINARY_NAME: devx-logs-linux-arm64

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Run tests
      run: go test .
    - name: Build
      run: GOOS=linux GOARCH=arm64 go build -o $BINARY_NAME main.go      
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.BINARY_NAME }}
        path: ${{ env.BINARY_NAME }}
