name: ci

env:
  BINARY_NAME: devx-logs-linux

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Run tests
        run: go test .
  upload:
    runs-on: ubuntu-latest
    needs: [test]
    # if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Build
        run: |
          GOOS=linux GOARCH=arm64 go build -o $BINARY_NAME-arm64 main.go      
          GOOS=linux GOARCH=amd64 go build -o $BINARY_NAME-amd64 main.go
      - uses: guardian/actions-riff-raff@main
        with:
          app: devx-logs
          stack: deploy
          deployments: |
            upload:
              type: aws-s3
              sources: ${{ env.BINARY_NAME }}-arm64,${{ env.BINARY_NAME }}-amd64
              parameters:
                bucket: amigo-data
                cacheControl: private
                publicReadAcl: false
