name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: guardian-devtools
      SKIP_NODE: true
      SKIP_GO: false
      GO_VERSION_FILE: ec2/go.mod
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
