name: upload

env:
  BINARY_NAME: devx-logs-linux

on:
  workflow_dispatch:
  workflow_run:
    workflows: [test]
    types: [completed]
    # branches: [main] TODO enable afterwards

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Build
        run: |
          GOOS=linux GOARCH=arm64 go build -o $BINARY_NAME-arm64 main.go      
          GOOS=linux GOARCH=amd64 go build -o $BINARY_NAME-amd64 main.go
      - uses: guardian/actions-riff-raff@latest
        with:
          app: devx-logs
          stack: deploy
          dryRun: true
          deployments: |
            upload:
              type: aws-s3
              sources: ${{ env.BINARY_NAME }}-arm64,${{ env.BINARY_NAME }}-amd64
              parameters:
                bucket: amigo-data
                cacheControl: private
                publicReadAcl: false
